### ISSUE TITLE
Audio breaks when user triggers input too soon

### ISSUE THREAD

**Issue by aewing** [lukehorvat/super-oscillator#2]
As seen on https://oscillator.js.org/,
If a user clicks or presses a key within the first few seconds, the audio fails to work for the duration of the session. There are no pertinent errors showing in the console.

I intend to look into this with #3, but wanted to document it in case I get side tracked.

**Comment by lukehorvat** [comment]
Weird, I can't seem to reproduce this bug.

Maybe it's due to [this](https://blog.google/products/chrome/improving-autoplay-chrome/)?

**Comment by aewing** [comment]
Perhaps. I'm not seeing the error anymore, though I've switched operating systems since.
