### ISSUE TITLE
Rewriting Keyboard Support & Possible UI Updates

### ISSUE THREAD

**Issue by aewing** [lukehorvat/super-oscillator#3]
As it stands, the user is only able to activate a single key on keypress.
I would like to rewrite the input support to resolve this issue, and given the desire to support key overlays and the input on my original PR, I wanted to take input on recommendations for the keyboard support and potential UI changes. I'm personally interested in mocking something up using React and styled-components (sans three.js) inspired by GarageBand's "Musical Typing".

Are we married to the 3D aspect of this project?
What do we think about utilizing React (with or without three.js [react-three-renderer])?
What do we think about using [styled-components](https://www.styled-components.com/)?
If we utilize React, how do we feel about using [parcel](https://github.com/parcel-bundler/parcel) for bundling?
What would we prefer for the keyboard mapping?
Would anyone like to mock up/recommend a UI configuration or make style suggestions?

I have some bandwidth to work on this over the weekend. Though I am not sure that I would be as productive in three.js, I am willing to take a crack at it if that is the preferred solution. I know that these are awfully opinionated recommendations and change the scope of the project quite a bit, so I will not be offended if this is not of interest to the project maintainer(s). I am interested in contributing whether or not these changes are agreeable.

**Comment by lukehorvat** [comment]
Yep, I'd like to keep it 3D. I agree that three.js can be a bit difficult to work with, but all of the other synthesizer implementations I've seen were 2D, so I wanted to do something different. I know that's not really a great justification, but it's a "for fun" creative project, so...

Also, my plan/hope was to eventually add VR support, which necessitates 3D.

If there's a way to use React *and* retain the 3D aspect, I'm open to it. But I haven't investigated the feasibility of that at all...

I think making a React-based 2D synthesizer (as a separate project) would be cool. 👍If that's a project you want to start, I would be interested in contributing to that. Feel free to use my [web-audio-oscillators](https://github.com/lukehorvat/web-audio-oscillators) package for generating sounds.

**Comment by lukehorvat** [comment]
I overlooked that you mentioned [react-three-renderer](https://github.com/toxicFork/react-three-renderer). Looks pretty cool, but is still in an "experimental" phase. If you/someone wants to do the hard work of seeing whether Super Oscillator plays nicely with react-three-renderer, I'd be very interested to see that. Unfortunately I don't have any free time right now to investigate that.

**Comment by aewing** [comment]
Fair enough. Best of luck with the UI changes.
